import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../comps/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Brainiac",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-5 h-screen">
          <div className="col-span-1 bg-sidebarbackground text-white">
            <Sidebar />
          </div>
          <div className="col-span-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
